name: umi-arx
channels:
  - robostack
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.24.4
  - click
  - pyzmq
  - pynput
  - pip
  - py-opencv
  - libopencv
  - scipy
  - omegaconf
  - av
  - threadpoolctl
  - zarr
  - numcodecs
  - pip:
    - atomics
    - spnav @ https://github.com/cheng-chi/spnav/archive/c1c938ebe3cc542db4685e0d13850ff1abfdb943.tar.gz